apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: dag-
  labels:
    workflows.argoproj.io/archive-strategy: "false"
spec:
  entrypoint: full
  # serviceAccountName: workflow
  # volumes:
  # - name: kaniko-secret
  #   secret:
  #     secretName: regcred
  #     items:
  #       - key: .dockerconfigjson
  #         path: config.json
  templates:
  - name: full
    dag:
      tasks:
      - name: task-a
        template: my-task
        arguments:
          parameters:
          - name: message
            value: This is task-a
      - name: task-b
        template: my-task
        arguments:
          parameters:
          - name: message
            value: This is task-b
      - name: task-c
        template: my-task
        arguments:
          parameters:
          - name: message
            value: This is task-c
      - name: task-d
        template: my-task
        arguments:
          parameters:
          - name: message
            value: This is task-d
        dependencies:
        - task-a
      - name: task-e
        template: my-task
        arguments:
          parameters:
          - name: message
            value: This is task-e
        dependencies:
        - task-a
      - name: task-f
        template: my-task
        arguments:
          parameters:
          - name: message
            value: This is task-f
        dependencies:
        - task-a
        - task-e
      - name: task-g
        template: my-task
        arguments:
          parameters:
          - name: message
            value: This is task-g
  - name: my-task
    inputs:
      parameters:
      - name: message
    container:
      image: alpine
      command: [echo]
      args:
      - "{{inputs.parameters.message}}"
